# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import model.category as module_0


def test_case_0():
    float_0 = 103.65
    list_0 = [float_0]
    float_1 = -2840.7768
    category_0 = module_0.Category(list_0, float_1)
    category_0.deactivate()
